project:
  type: book
  output-dir: docs/

book:
  title: "R ile Veri Dönüşümü"
  author: "Servet Çetin"
  reader-mode: true
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - intro.qmd
    - part: veri_donusum.qmd
      chapters:
        - veri_manipulasyonu.qmd
        - veri_temizleme.qmd
  downloads: [pdf, docx]
  sharing: [twitter, linkedin]
  cover-image: cover.png
  repo-url: https://github.com/cetinservet/dygmveri

bibliography: references.bib

format:
  html:
    code-copy: true
    code-link: true
    code-fold: false
    code-tools: false
    toc-title: İçindekiler
    theme:
      light: cosmo
      dark: darkly
    cover-image: cover.png
  pdf:
    documentclass: scrreprt
    toc-title: İçindekiler
    cover-image: cover.png
    mainfont: "Times New Roman"
  docx:
    toc: true
    toc-title: İçindekiler
    number-sections: true
    mainfont: "Times New Roman"

editor: visual

